#Spring
spring:
    #MessageQueue
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 30000
    virtual-host: ${RABBITMQ_VHOST}
  cloud:
    refresh:
      never-refreshable:
        - com.netflix.discovery.EurekaClient
        - com.netflix.discovery.DiscoveryClient
        - org.springframework.cloud.config.server.config.ConfigServerHealthIndicator
    #Stream ->
    function:
      definition: orderEventConsumer
    stream:
      bindings:
        orderEventConsumer-in-0:
          destination: ecomm.exchange.order
          group: notification
          binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_BROKER}
#      kafka:
#        binder:
#          brokers: ecomm-kafka-ishon.i.aivencloud.com:13199
#          jaas:
#            loginModule: org.apache.kafka.common.security.scram.ScramLoginModule
#            controlFlag: required
#            options:
#              username:
#              password:
#          configuration:
#            security.protocol: SASL_SSL
#            sasl.mechanism: SCRAM-SHA-256
#            ssl.truststore.location: 'ca.pem'
#            ssl.truststore.type: 'PEM'
#      rabbit:
#        bindings:
#          orderEventConsumer-in-0:
#              consumer:
#                binding-routing-key: order.*

  #MAIL
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#Notification Queue and Exchange
#rabbitmq:
#  exchange:
#    name: ecomm.exchange
#  queue:
#    name: notification.queue
#  routing:
#    order: order.*

#Logging
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n'
  level:
    root: INFO
  file:
    name: Logs/${spring.application.name}.log

#Actuator + Zipkin
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      circuitbreakers:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,busrefresh,refresh,prometheus,circuitbreakers
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}

#Eureka
eureka:
  client:
    refresh:
      enable: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    instanceId: ${spring.application.name}:${server.port}

#Server
server:
  port: 8085
