#Spring
spring:
  #Oauth2 - Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_JWT_ISSUER}
          jwk-set-uri: ${KEYCLOAK_JWK_URI}
  #Database POSTGRES
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    #MessageQueue
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 30000
    virtual-host: ${RABBITMQ_VHOST}
  cloud:
    refresh:
      never-refreshable:
        - com.netflix.discovery.EurekaClient
        - com.netflix.discovery.DiscoveryClient
        - org.springframework.cloud.config.server.config.ConfigServerHealthIndicator

  #Cloud Streams ->
    stream:
      bindings:
        createOrder-out-0:
          destination: ecomm.exchange.order
          content-type: application/json
          binder: kafka
        cancelOrder-out-0:
          destination: ecomm.exchange.order
          content-type: application/json
          binder: kafka
        updateOrderStatus-out-0:
          destination: ecomm.exchange.order
          content-type: application/json
          binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_BROKER}
#      kafka:
#        binder:
#          brokers: ecomm-kafka-ishon.i.aivencloud.com:13199
#          jaas:
#            loginModule: org.apache.kafka.common.security.scram.ScramLoginModule
#            controlFlag: required
#            options:
#              username:
#              password:
#          configuration:
#            security.protocol: SASL_SSL
#            sasl.mechanism: SCRAM-SHA-256
#            ssl.truststore.location: 'ca.pem'
#            ssl.truststore.type: 'PEM'

#      rabbit:
#        bindings:
#          createOrder-out-0:
#            producer:
#              routing-key-expression: "'order.created'"
#          cancelOrder-out-0:
#            producer:
#              routing-key-expression: "'order.cancelled'"
#          updateOrderStatus-out-0:
#            producer:
#              routing-key-expression: headers['target_key']
#Order : Queue and Exchange
exchange:
#  exchange:
#    name: ecomm.exchange
  key:
    created: order.created
    cancelled: order.cancelled
    delivered: order.delivered
    confirmed: order.confirmed
    shipped: order.shipped

#Logging
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n'
  level:
    root: INFO
  file:
    name: Logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: Logs/${spring.application.name}.%d{yyyy-MM-dd}.log
      max-history: 1
      clean-history-on-start: true
#Actuator + Zipkin
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      circuitbreakers:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,busrefresh,refresh,prometheus,circuitbreakers
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}

#Eureka
eureka:
  client:
    refresh:
      enable: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    instanceId: ${spring.application.name}:${server.port}

#CircuitBreaker
resilience4j:
  circuitbreaker:
    instances:
      #Breaker for Product
      productBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException

      #Breaker for User
      userBreaker:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException

  retry:
    instances:
      #Retry for Product
      productRetry:
        maxAttempts: 3
        waitDuration: 500ms
        intervalFunction:
          type: exponential
          initialInterval: 500ms
          multiplier: 1.5
          maxInterval: 5s
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
      #Retry for User
      userRetry:
        maxAttempts: 3
        waitDuration: 500ms
        intervalFunction:
          type: exponential
          initialInterval: 500ms
          multiplier: 1.5
          maxInterval: 5s
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
  ratelimiter:
    instances:
      orderRate:
        timeout-duration: 0
        limit-refresh-period: 5s
        limit-for-period: 10

#Server
server:
  port: 8084
